2024-08-14 01:41:26,192:ERROR:Exception during reset or similar
Traceback (most recent call last):
  File "/Users/lucian/Desktop/Github/ASPJ24/aspj24/lib/python3.11/site-packages/pymysql/connections.py", line 782, in _read_bytes
    data = self._rfile.read(num_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucian/Desktop/Github/ASPJ24/aspj24/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 988, in _finalize_fairy
    fairy._reset(
  File "/Users/lucian/Desktop/Github/ASPJ24/aspj24/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 1438, in _reset
    pool._dialect.do_rollback(self)
  File "/Users/lucian/Desktop/Github/ASPJ24/aspj24/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 692, in do_rollback
    dbapi_connection.rollback()
  File "/Users/lucian/Desktop/Github/ASPJ24/aspj24/lib/python3.11/site-packages/pymysql/connections.py", line 493, in rollback
    self._read_ok_packet()
  File "/Users/lucian/Desktop/Github/ASPJ24/aspj24/lib/python3.11/site-packages/pymysql/connections.py", line 453, in _read_ok_packet
    pkt = self._read_packet()
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/lucian/Desktop/Github/ASPJ24/aspj24/lib/python3.11/site-packages/pymysql/connections.py", line 744, in _read_packet
    packet_header = self._read_bytes(4)
                    ^^^^^^^^^^^^^^^^^^^
  File "/Users/lucian/Desktop/Github/ASPJ24/aspj24/lib/python3.11/site-packages/pymysql/connections.py", line 788, in _read_bytes
    raise err.OperationalError(
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query ([Errno 54] Connection reset by peer)')
2024-08-14 01:41:47,080:WARNING: * Debugger is active!
2024-08-14 01:44:54,546:WARNING: * Debugger is active!
2024-08-14 01:45:59,142:WARNING: * Debugger is active!
2024-08-14 01:46:40,922:WARNING: * Debugger is active!
2024-08-14 01:47:08,390:WARNING: * Debugger is active!
2024-08-14 01:49:11,348:WARNING: * Debugger is active!
2024-08-14 01:50:10,224:WARNING: * Debugger is active!
2024-08-14 01:50:39,714:WARNING: * Debugger is active!
2024-08-14 01:53:50,269:WARNING: * Debugger is active!
2024-08-14 02:00:45,928:WARNING: * Debugger is active!
2024-08-14 02:02:33,243:WARNING: * Debugger is active!
2024-08-14 02:02:55,165:WARNING: * Debugger is active!
2024-08-14 02:06:20,090:WARNING: * Debugger is active!
2024-08-14 02:10:44,511:WARNING: * Debugger is active!
2024-08-14 02:13:46,408:WARNING: * Debugger is active!
2024-08-14 02:14:53,328:ERROR:Status code 403 from https://nominatim.openstreetmap.org/search: ERROR - 403 Client Error: Forbidden for url: https://nominatim.openstreetmap.org/search?q=Singapore+%28Queenstown+Estate%29%2C++SG&format=jsonv2&addressdetails=1&limit=1
2024-08-14 02:14:56,295:ERROR:Status code 403 from https://nominatim.openstreetmap.org/search: ERROR - 403 Client Error: Forbidden for url: https://nominatim.openstreetmap.org/search?q=Singapore+%28Queenstown+Estate%29%2C+SG&format=jsonv2&addressdetails=1&limit=1
2024-08-14 02:16:34,246:WARNING: * Debugger is active!
2024-08-14 02:21:02,219:WARNING: * Debugger is active!
2024-08-14 02:21:37,742:WARNING: * Debugger is active!
2024-08-14 02:21:48,101:WARNING: * Debugger is active!
2024-08-14 02:22:27,928:WARNING: * Debugger is active!
2024-08-14 02:24:37,743:WARNING: * Debugger is active!
2024-08-14 02:25:10,936:WARNING: * Debugger is active!
2024-08-14 02:39:59,154:WARNING: * Debugger is active!
2024-08-14 02:41:29,847:WARNING: * Debugger is active!
